# Generated by Django 4.2.11 on 2024-04-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
