# Generated by Django 4.2.11 on 2024-04-05 15:31

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_recipe_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=recipe.models.get_default_image, upload_to='recipe_images/'),
        ),
    ]
