# Generated by Django 4.2.11 on 2024-04-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_remove_recipe_rating_comment_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
        migrations.AddField(
            model_name='comment',
            name='stars',
            field=models.IntegerField(default=0),
        ),
    ]
