# Generated by Django 4.2.11 on 2024-04-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0011_remove_comment_rating_comment_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='stars',
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=0),
        ),
    ]
